[package]
name = "aoc-visualisation"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
ndarray = "0.16.1"
ratatui = "0.29.0"
tracing = "0.1.41"

[dev-dependencies]
tracing-subscriber = "0.3.19"

